### ISSUE TITLE
why not support windows ?

### ISSUE THREAD

**Issue by suntsh** [cosmo0920/tesseractocr-capi-go#1]
why not support windows ?

**Comment by cosmo0920** [comment]
This is because Windows dose not have `pkg-config` command.
Lack of `pkg-config` makes hard to find dependent library.

Is there any good way to find dependent library in Windows?

**Comment by cosmo0920** [comment]
@suntsh Any response?

I've tried to find `Tesseract-OCR` installed directory.

I used `PowerShell` like this:

`find-tesseract-ocr-installed-dir.ps1`:

``` powershell
$path = "HKLM:\SOFTWARE\Tesseract-OCR"
$item = Get-ItemProperty $path
Write-Host $item.InstallDir
```

``` log
PS> .\find-tesseract-ocr-installed-dir.ps1
C:\Program Files (x86)\Tesseract-OCR
```

Unfortunately, Tesseract-OCR Windows binary is only provided 32bit version.
And I didn't find how to use cgo under Windows environment, though.

**Comment by cosmo0920** [comment]
I close this issue because no response for a several months.
I does not use Golang with cgo on Windows.
